export const GET_ALL_PROJECT_REQUEST = "GET_ALL_PROJECT_REQUEST";
export const GET_ALL_PROJECT_SUCCESS = "GET_ALL_PROJECT_SUCCESS";
export const GET_ALL_PROJECT_FAIL = "GET_ALL_PROJECT_FAIL";

export const GET_SINGLE_PROJECT_REQUEST = "GET_SINGLE_PROJECT_REQUEST";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_FAIL = "GET_SINGLE_PROJECT_FAIL";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const APPLY_PROJECT_REQUEST = "APPLY_PROJECT_REQUEST";
export const APPLY_PROJECT_SUCCESS = "APPLY_PROJECT_SUCCESS";
export const APPLY_PROJECT_FAIL = "APPLY_PROJECT_FAIL";

export const HIRE_DEVELOPER_REQUEST = "HIRE_DEVELOPER_REQUEST";
export const HIRE_DEVELOPER_SUCCESS = "HIRE_DEVELOPER_SUCCESS";
export const HIRE_DEVELOPER_FAIL = "HIRE_DEVELOPER_FAIL";
